/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiconverter;

/**
 *
 * @author ravindu
 */
public class UITemplate {

    static String header = "<!doctype html>\n"
            + "<html lang=\"en\">\n"
            + "  <head>\n"
            + "    <!-- Required meta tags -->\n"
            + "    <meta charset=\"utf-8\">\n"
            + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n"
            + "\n"
            + "    <!-- Bootstrap CSS -->\n"
            + "    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n"
            + "\n"
            + "    <title>Hello, world!</title>\n"
            + "<style>\n"
            + "/*\n"
            + "img {\n"
            + "    vertical-align: middle;\n"
            + "}\n"
            + "\n"
            + ".img-responsive {\n"
            + "    display: block;\n"
            + "    height: auto;\n"
            + "    max-width: 100%;\n"
            + "}\n"
            + "\n"
            + ".img-rounded {\n"
            + "    border-radius: 3px;\n"
            + "}\n"
            + "\n"
            + ".img-thumbnail {\n"
            + "    background-color: #fff;\n"
            + "    border: 1px solid #ededf0;\n"
            + "    border-radius: 3px;\n"
            + "    display: inline-block;\n"
            + "    height: auto;\n"
            + "    line-height: 1.428571429;\n"
            + "    max-width: 100%;\n"
            + "    moz-transition: all .2s ease-in-out;\n"
            + "    o-transition: all .2s ease-in-out;\n"
            + "    padding: 2px;\n"
            + "    transition: all .2s ease-in-out;\n"
            + "    webkit-transition: all .2s ease-in-out;\n"
            + "}\n"
            + "\n"
            + ".img-circle {\n"
            + "    border-radius: 50%;\n"
            + "}\n"
            + "*/\n"
            + ".timeline-centered {\n"
            + "    position: relative;\n"
            + "    margin-bottom: 30px;\n"
            + "}\n"
            + "\n"
            + "    .timeline-centered:before, .timeline-centered:after {\n"
            + "        content: \" \";\n"
            + "        display: table;\n"
            + "    }\n"
            + "\n"
            + "    .timeline-centered:after {\n"
            + "        clear: both;\n"
            + "    }\n"
            + "\n"
            + "    .timeline-centered:before, .timeline-centered:after {\n"
            + "        content: \" \";\n"
            + "        display: table;\n"
            + "    }\n"
            + "\n"
            + "    .timeline-centered:after {\n"
            + "        clear: both;\n"
            + "    }\n"
            + "\n"
            + "    .timeline-centered:before {\n"
            + "        content: '';\n"
            + "        position: absolute;\n"
            + "        display: block;\n"
            + "        width: 4px;\n"
            + "        background: #f5f5f6;\n"
            + "        /*left: 50%;*/\n"
            + "        top: 20px;\n"
            + "        bottom: 20px;\n"
            + "        margin-left: 30px;\n"
            + "    }\n"
            + "\n"
            + "    .timeline-centered .timeline-entry {\n"
            + "        position: relative;\n"
            + "        /*width: 50%;\n"
            + "        float: right;*/\n"
            + "        margin-top: 5px;\n"
            + "        margin-left: 30px;\n"
            + "        margin-bottom: 10px;\n"
            + "        clear: both;\n"
            + "    }\n"
            + "\n"
            + "        .timeline-centered .timeline-entry:before, .timeline-centered .timeline-entry:after {\n"
            + "            content: \" \";\n"
            + "            display: table;\n"
            + "        }\n"
            + "\n"
            + "        .timeline-centered .timeline-entry:after {\n"
            + "            clear: both;\n"
            + "        }\n"
            + "\n"
            + "        .timeline-centered .timeline-entry:before, .timeline-centered .timeline-entry:after {\n"
            + "            content: \" \";\n"
            + "            display: table;\n"
            + "        }\n"
            + "\n"
            + "        .timeline-centered .timeline-entry:after {\n"
            + "            clear: both;\n"
            + "        }\n"
            + "\n"
            + "        .timeline-centered .timeline-entry.begin {\n"
            + "            margin-bottom: 0;\n"
            + "        }\n"
            + "\n"
            + "        .timeline-centered .timeline-entry.left-aligned {\n"
            + "            float: left;\n"
            + "        }\n"
            + "\n"
            + "            .timeline-centered .timeline-entry.left-aligned .timeline-entry-inner {\n"
            + "                margin-left: 0;\n"
            + "                margin-right: -18px;\n"
            + "            }\n"
            + "\n"
            + "                .timeline-centered .timeline-entry.left-aligned .timeline-entry-inner .timeline-time {\n"
            + "                    left: auto;\n"
            + "                    right: -100px;\n"
            + "                    text-align: left;\n"
            + "                }\n"
            + "\n"
            + "                .timeline-centered .timeline-entry.left-aligned .timeline-entry-inner .timeline-icon {\n"
            + "                    float: right;\n"
            + "                }\n"
            + "\n"
            + "                .timeline-centered .timeline-entry.left-aligned .timeline-entry-inner .timeline-label {\n"
            + "                    margin-left: 0;\n"
            + "                    margin-right: 70px;\n"
            + "                }\n"
            + "\n"
            + "                    .timeline-centered .timeline-entry.left-aligned .timeline-entry-inner .timeline-label:after {\n"
            + "                        left: auto;\n"
            + "                        right: 0;\n"
            + "                        margin-left: 0;\n"
            + "                        margin-right: -9px;\n"
            + "                        -moz-transform: rotate(180deg);\n"
            + "                        -o-transform: rotate(180deg);\n"
            + "                        -webkit-transform: rotate(180deg);\n"
            + "                        -ms-transform: rotate(180deg);\n"
            + "                        transform: rotate(180deg);\n"
            + "                    }\n"
            + "\n"
            + "        .timeline-centered .timeline-entry .timeline-entry-inner {\n"
            + "            position: relative;\n"
            + "            margin-left: -20px;\n"
            + "        }\n"
            + "\n"
            + "            .timeline-centered .timeline-entry .timeline-entry-inner:before, .timeline-centered .timeline-entry .timeline-entry-inner:after {\n"
            + "                content: \" \";\n"
            + "                display: table;\n"
            + "            }\n"
            + "\n"
            + "            .timeline-centered .timeline-entry .timeline-entry-inner:after {\n"
            + "                clear: both;\n"
            + "            }\n"
            + "\n"
            + "            .timeline-centered .timeline-entry .timeline-entry-inner:before, .timeline-centered .timeline-entry .timeline-entry-inner:after {\n"
            + "                content: \" \";\n"
            + "                display: table;\n"
            + "            }\n"
            + "\n"
            + "            .timeline-centered .timeline-entry .timeline-entry-inner:after {\n"
            + "                clear: both;\n"
            + "            }\n"
            + "\n"
            + "            .timeline-centered .timeline-entry .timeline-entry-inner .timeline-time {\n"
            + "                position: absolute;\n"
            + "                left: -100px;\n"
            + "                text-align: right;\n"
            + "                padding: 10px;\n"
            + "                -webkit-box-sizing: border-box;\n"
            + "                -moz-box-sizing: border-box;\n"
            + "                box-sizing: border-box;\n"
            + "            }\n"
            + "\n"
            + "                .timeline-centered .timeline-entry .timeline-entry-inner .timeline-time > span {\n"
            + "                    display: block;\n"
            + "                }\n"
            + "\n"
            + "                    .timeline-centered .timeline-entry .timeline-entry-inner .timeline-time > span:first-child {\n"
            + "                        font-size: 15px;\n"
            + "                        font-weight: bold;\n"
            + "                    }\n"
            + "\n"
            + "                    .timeline-centered .timeline-entry .timeline-entry-inner .timeline-time > span:last-child {\n"
            + "                        font-size: 12px;\n"
            + "                    }\n"
            + "\n"
            + "            .timeline-centered .timeline-entry .timeline-entry-inner .timeline-icon {\n"
            + "                background: #fff;\n"
            + "                color: #737881;\n"
            + "                display: block;\n"
            + "                width: 40px;\n"
            + "                height: 40px;\n"
            + "                -webkit-background-clip: padding-box;\n"
            + "                -moz-background-clip: padding;\n"
            + "                background-clip: padding-box;\n"
            + "                -webkit-border-radius: 20px;\n"
            + "                -moz-border-radius: 20px;\n"
            + "                border-radius: 20px;\n"
            + "                text-align: center;\n"
            + "                -moz-box-shadow: 0 0 0 5px #f5f5f6;\n"
            + "                -webkit-box-shadow: 0 0 0 5px #f5f5f6;\n"
            + "                box-shadow: 0 0 0 5px #f5f5f6;\n"
            + "                line-height: 40px;\n"
            + "                font-size: 15px;\n"
            + "                float: left;\n"
            + "            }\n"
            + "\n"
            + "                .timeline-centered .timeline-entry .timeline-entry-inner .timeline-icon.bg-primary {\n"
            + "                    background-color: #303641;\n"
            + "                    color: #fff;\n"
            + "                }\n"
            + "\n"
            + "                .timeline-centered .timeline-entry .timeline-entry-inner .timeline-icon.bg-secondary {\n"
            + "                    background-color: #ee4749;\n"
            + "                    color: #fff;\n"
            + "                }\n"
            + "\n"
            + "                .timeline-centered .timeline-entry .timeline-entry-inner .timeline-icon.bg-success {\n"
            + "                    background-color: #00a651;\n"
            + "                    color: #fff;\n"
            + "                }\n"
            + "\n"
            + "                .timeline-centered .timeline-entry .timeline-entry-inner .timeline-icon.bg-info {\n"
            + "                    background-color: #21a9e1;\n"
            + "                    color: #fff;\n"
            + "                }\n"
            + "\n"
            + "                .timeline-centered .timeline-entry .timeline-entry-inner .timeline-icon.bg-warning {\n"
            + "                    background-color: #fad839;\n"
            + "                    color: #fff;\n"
            + "                }\n"
            + "\n"
            + "                .timeline-centered .timeline-entry .timeline-entry-inner .timeline-icon.bg-danger {\n"
            + "                    background-color: #cc2424;\n"
            + "                    color: #fff;\n"
            + "                }\n"
            + "\n"
            + "            .timeline-centered .timeline-entry .timeline-entry-inner .timeline-label {\n"
            + "                position: relative;\n"
            + "                background: #f5f5f6;\n"
            + "                padding: 1em;\n"
            + "                margin-left: 60px;\n"
            + "                -webkit-background-clip: padding-box;\n"
            + "                -moz-background-clip: padding;\n"
            + "                background-clip: padding-box;\n"
            + "                -webkit-border-radius: 3px;\n"
            + "                -moz-border-radius: 3px;\n"
            + "                border-radius: 3px;\n"
            + "            }\n"
            + "\n"
            + "                .timeline-centered .timeline-entry .timeline-entry-inner .timeline-label:after {\n"
            + "                    content: '';\n"
            + "                    display: block;\n"
            + "                    position: absolute;\n"
            + "                    width: 0;\n"
            + "                    height: 0;\n"
            + "                    border-style: solid;\n"
            + "                    border-width: 9px 9px 9px 0;\n"
            + "                    border-color: transparent #f5f5f6 transparent transparent;\n"
            + "                    left: 0;\n"
            + "                    top: 10px;\n"
            + "                    margin-left: -9px;\n"
            + "                }\n"
            + "\n"
            + "                .timeline-centered .timeline-entry .timeline-entry-inner .timeline-label h2, .timeline-centered .timeline-entry .timeline-entry-inner .timeline-label p {\n"
            + "                    color: #737881;\n"
            + "                    font-family: \"Noto Sans\",sans-serif;\n"
            + "                    font-size: 12px;\n"
            + "                    margin: 0;\n"
            + "                    line-height: 1.428571429;\n"
            + "                }\n"
            + "\n"
            + "                    .timeline-centered .timeline-entry .timeline-entry-inner .timeline-label p + p {\n"
            + "                        margin-top: 15px;\n"
            + "                    }\n"
            + "\n"
            + "                .timeline-centered .timeline-entry .timeline-entry-inner .timeline-label h2 {\n"
            + "                    font-size: 16px;\n"
            + "                    margin-bottom: 10px;\n"
            + "                }\n"
            + "\n"
            + "                    .timeline-centered .timeline-entry .timeline-entry-inner .timeline-label h2 a {\n"
            + "                        color: #303641;\n"
            + "                    }\n"
            + "\n"
            + "                    .timeline-centered .timeline-entry .timeline-entry-inner .timeline-label h2 span {\n"
            + "                        -webkit-opacity: .6;\n"
            + "                        -moz-opacity: .6;\n"
            + "                        opacity: .6;\n"
            + "                        -ms-filter: alpha(opacity=60);\n"
            + "                        filter: alpha(opacity=60);\n"
            + "                    }\n"
            + "\n"
            + "\n"
            + "</style>"
            + "  </head>\n"
            + "  <body>\n";
    static String footer = "\n\n<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script> \n"
            + "    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script> \n"
            + "    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script> \n\n\n"
            + "  </body>\n"
            + "</html>";
}
